//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneLibrary {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsMsg() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneLibrary.ErrorsMsg", typeof(ErrorsMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка соединения с базой. Возможно неправильно введен логин,
        ///пароль или имя сервера баз данных. Проверьте также, не  включен ли 
        ///CapsLock на клавиатуре..
        /// </summary>
        public static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № ИКЛ &quot;{0}&quot; уже существует в базе. 
        ///Номер ИКЛ должен быть уникальным. .
        /// </summary>
        public static string DublicateCardNumIKL {
            get {
                return ResourceManager.GetString("DublicateCardNumIKL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № ИК-2 &quot;{0}&quot; уже существует в базе. 
        ///Номер ИК-2 должен быть уникальным. .
        /// </summary>
        public static string DublicateCardNumIKL2 {
            get {
                return ResourceManager.GetString("DublicateCardNumIKL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Категория объекта&quot; не может быть пустым.
        /// </summary>
        public static string EmptyClassObjectNameField {
            get {
                return ResourceManager.GetString("EmptyClassObjectNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Комментарий&quot; не может быть пустым.
        /// </summary>
        public static string EmptyComment {
            get {
                return ResourceManager.GetString("EmptyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Адрес&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyDivAddrField {
            get {
                return ResourceManager.GetString("EmptyDivAddrField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Название&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyDivNameField {
            get {
                return ResourceManager.GetString("EmptyDivNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Телефон&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyDivPhoneField {
            get {
                return ResourceManager.GetString("EmptyDivPhoneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Подразделение&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyExpDivField {
            get {
                return ResourceManager.GetString("EmptyExpDivField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Логин&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyExpLoginField {
            get {
                return ResourceManager.GetString("EmptyExpLoginField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Имя&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyExpNameField {
            get {
                return ResourceManager.GetString("EmptyExpNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Пароль&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyExpPasswordField {
            get {
                return ResourceManager.GetString("EmptyExpPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Отчество&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyExpPatronicField {
            get {
                return ResourceManager.GetString("EmptyExpPatronicField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Должность&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyExpPostField {
            get {
                return ResourceManager.GetString("EmptyExpPostField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Подпись&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyExpSignField {
            get {
                return ResourceManager.GetString("EmptyExpSignField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Фамилия&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyExpSurnameField {
            get {
                return ResourceManager.GetString("EmptyExpSurnameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указано имя фильтра.
        /// </summary>
        public static string EmptyFilterName {
            get {
                return ResourceManager.GetString("EmptyFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Описание&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyFreqDescField {
            get {
                return ResourceManager.GetString("EmptyFreqDescField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Частота по умолчанию&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyFreqFreqField {
            get {
                return ResourceManager.GetString("EmptyFreqFreqField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Название&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyFreqNameField {
            get {
                return ResourceManager.GetString("EmptyFreqNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Адрес(место проишествия)&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2AddressField {
            get {
                return ResourceManager.GetString("EmptyIk2AddressField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;№ ИК-2&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2CardNumberField {
            get {
                return ResourceManager.GetString("EmptyIk2CardNumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;№ Угол. дела&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2CaseNumberField {
            get {
                return ResourceManager.GetString("EmptyIk2CaseNumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Категория&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2ClassField {
            get {
                return ResourceManager.GetString("EmptyIk2ClassField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Код горрайлинограна&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2LinField {
            get {
                return ResourceManager.GetString("EmptyIk2LinField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Код МВД, ГУВД, УВД субъекта федерации&quot; 
        ///не должно быть пустым.
        /// </summary>
        public static string EmptyIk2MvdField {
            get {
                return ResourceManager.GetString("EmptyIk2MvdField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Орган назначивший экспертизу&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2OrganField {
            get {
                return ResourceManager.GetString("EmptyIk2OrganField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Вид объекта&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2SortField {
            get {
                return ResourceManager.GetString("EmptyIk2SortField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Статья и часть УК&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2UkField {
            get {
                return ResourceManager.GetString("EmptyIk2UkField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Потерпевший&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2VictimField {
            get {
                return ResourceManager.GetString("EmptyIk2VictimField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Год постановки объекта на учет&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIk2YearField {
            get {
                return ResourceManager.GetString("EmptyIk2YearField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;№ ИКЛ&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIklCardNumberField {
            get {
                return ResourceManager.GetString("EmptyIklCardNumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;№ уголовного дела&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIklCaseNumberField {
            get {
                return ResourceManager.GetString("EmptyIklCaseNumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Категория&quot; не может быть пустым.
        /// </summary>
        public static string EmptyIklClassField {
            get {
                return ResourceManager.GetString("EmptyIklClassField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Орган назначивший экспертизу&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIklOrganizationField {
            get {
                return ResourceManager.GetString("EmptyIklOrganizationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Проверяемое лицо&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIklSuspectField {
            get {
                return ResourceManager.GetString("EmptyIklSuspectField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Статья и часть УК&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyIklUkField {
            get {
                return ResourceManager.GetString("EmptyIklUkField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Код райлиноргана&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyLinCodeField {
            get {
                return ResourceManager.GetString("EmptyLinCodeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Описание&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyLinOrganField {
            get {
                return ResourceManager.GetString("EmptyLinOrganField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Локус&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyLocusField {
            get {
                return ResourceManager.GetString("EmptyLocusField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Имя пользователя&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyLogin {
            get {
                return ResourceManager.GetString("EmptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Код МВД&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyMvdCodeField {
            get {
                return ResourceManager.GetString("EmptyMvdCodeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Имя&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyMvdNameField {
            get {
                return ResourceManager.GetString("EmptyMvdNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Краткое имя&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyMvdShortNameField {
            get {
                return ResourceManager.GetString("EmptyMvdShortNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер карточки родителя должен быть указан.
        /// </summary>
        public static string EmptyOneParent {
            get {
                return ResourceManager.GetString("EmptyOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Пароль&quot; не заполнено. 
        ///Продолжить сохранение данных?.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Название должности&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyPostNameField {
            get {
                return ResourceManager.GetString("EmptyPostNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название роли не должно быть пустым.
        /// </summary>
        public static string EmptyRoleNameField {
            get {
                return ResourceManager.GetString("EmptyRoleNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Сервер&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyServer {
            get {
                return ResourceManager.GetString("EmptyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Вид объекта&quot; не должно быть пустым.
        /// </summary>
        public static string EmptySortObjectNameField {
            get {
                return ResourceManager.GetString("EmptySortObjectNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Номер&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyUKArtclField {
            get {
                return ResourceManager.GetString("EmptyUKArtclField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Описание&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyUKNoteField {
            get {
                return ResourceManager.GetString("EmptyUKNoteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Текст&quot; не должно быть пустым.
        /// </summary>
        public static string EmptyUKTextField {
            get {
                return ResourceManager.GetString("EmptyUKTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление не возможно, так как имеются элементы в 
        ///базе данных использующие эту запись.
        /// </summary>
        public static string errDbViolated {
            get {
                return ResourceManager.GetString("errDbViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диапазаон должен быть представлен значениями даты.
        /// </summary>
        public static string ErrorDateBetween {
            get {
                return ResourceManager.GetString("ErrorDateBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значения списка {0} должны быть датами.
        /// </summary>
        public static string ErrorDateList {
            get {
                return ResourceManager.GetString("ErrorDateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение должно быть правильной датой.
        /// </summary>
        public static string ErrorDateUserValue {
            get {
                return ResourceManager.GetString("ErrorDateUserValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля {0} должно быть датой.
        /// </summary>
        public static string ErrorDateValue {
            get {
                return ResourceManager.GetString("ErrorDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В одном локусе не может быть двух аллелей с одинаковым наименованием.
        /// </summary>
        public static string ErrorDublicateAlleleName {
            get {
                return ResourceManager.GetString("ErrorDublicateAlleleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аллель должна иметь название и значение.
        /// </summary>
        public static string ErrorEmptyAlleleNameOrVal {
            get {
                return ResourceManager.GetString("ErrorEmptyAlleleNameOrVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В полях ввода представлены не допустимые значения.
        /// </summary>
        public static string ErrorFieldVal {
            get {
                return ResourceManager.GetString("ErrorFieldVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный формат ввода.
        /// </summary>
        public static string ErrorFormat {
            get {
                return ResourceManager.GetString("ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диапазон для поля &quot;{0}&quot; должен быть 
        ///представлен двумя числовыми значениями.
        /// </summary>
        public static string ErrorIntBetween {
            get {
                return ResourceManager.GetString("ErrorIntBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значения списка для поля &quot;{0}&quot; должны быть числовыми.
        /// </summary>
        public static string ErrorIntList {
            get {
                return ResourceManager.GetString("ErrorIntList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля &quot;{0}&quot; должно быть числом.
        /// </summary>
        public static string ErrorIntValue {
            get {
                return ResourceManager.GetString("ErrorIntValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В поле &quot;{0}&quot; могут содержаться только цифры 
        ///или знак десятичного разделителя - точка.
        /// </summary>
        public static string ErrorNotNumber {
            get {
                return ResourceManager.GetString("ErrorNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диапазон для поля &quot;{0}&quot; должен быть 
        ///представлен двумя значениями.
        /// </summary>
        public static string ErrorStringBetween {
            get {
                return ResourceManager.GetString("ErrorStringBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина строки для поля &quot;{0}&quot; не должна превышать {1} символов.
        /// </summary>
        public static string ErrorStringLength {
            get {
                return ResourceManager.GetString("ErrorStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество несовпадающих аллелей - {0}. Количество аллелей в следе, должно быть {1} или {2}.
        /// </summary>
        public static string ErrorTwoBlend1 {
            get {
                return ResourceManager.GetString("ErrorTwoBlend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл {0} не найден.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество аллелей для локуса в карточке ИКЛ не может быть более двух.
        /// </summary>
        public static string IklAlleleCount {
            get {
                return ResourceManager.GetString("IklAlleleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список должен содержать хотя бы одну карточку ИК-2.
        /// </summary>
        public static string ListNotConsistIk2 {
            get {
                return ResourceManager.GetString("ListNotConsistIk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для представленных карточек, не найдены совпадающие локусы.
        ///Такое возможно, если у одной из карточек не заполнен профиль
        ///или карточки с заданным номером не существует..
        /// </summary>
        public static string LocusesListIsEmpty {
            get {
                return ResourceManager.GetString("LocusesListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбраны записи.
        /// </summary>
        public static string NonSelectRow {
            get {
                return ResourceManager.GetString("NonSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка {0} не найдена в базе данных.
        /// </summary>
        public static string NotCardFound {
            get {
                return ResourceManager.GetString("NotCardFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль подтврежден не правильно.
        /// </summary>
        public static string NotConfirmPassword {
            get {
                return ResourceManager.GetString("NotConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В поле &quot;{0}&quot; должна находиться дата. Формат даты &quot;ДД.ММ.ГГГГ&quot;.
        /// </summary>
        public static string NotDate {
            get {
                return ResourceManager.GetString("NotDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка смеси должна быть выбрана в 
        ///результатах поиска.
        /// </summary>
        public static string NotFindBlend {
            get {
                return ResourceManager.GetString("NotFindBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено соответствующее значение.
        /// </summary>
        public static string NotFoundValue {
            get {
                return ResourceManager.GetString("NotFoundValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для получения отчетности, необходимо иметь установить
        /// на компьютере пользователя программный продукт 
        ///Microsoft Excel (версии 2000-20007).
        /// </summary>
        public static string NotInstallExcel {
            get {
                return ResourceManager.GetString("NotInstallExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В поле &quot;{0}&quot; могут содержаться только цифры.
        /// </summary>
        public static string NotInteger {
            get {
                return ResourceManager.GetString("NotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не реализован виртуальный метод.
        /// </summary>
        public static string NotRealizeVirtualMethod {
            get {
                return ResourceManager.GetString("NotRealizeVirtualMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбранны поля для отображения в отчете.
        /// </summary>
        public static string NotSelectedReportFIeld {
            get {
                return ResourceManager.GetString("NotSelectedReportFIeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определен тип карточки.
        /// </summary>
        public static string NotValidCardKind {
            get {
                return ResourceManager.GetString("NotValidCardKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;КИН карточки&quot; не может быть пустым 
        ///и должно содержать только цифры.
        /// </summary>
        public static string NotValidChild {
            get {
                return ResourceManager.GetString("NotValidChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не допустимый формат файла.
        /// </summary>
        public static string NotValidFileFormat {
            get {
                return ResourceManager.GetString("NotValidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не допустимый символ в строке поиска.
        /// </summary>
        public static string NotValidFindSimbol {
            get {
                return ResourceManager.GetString("NotValidFindSimbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В поле {0} могут содержаться только цифры и запятые с пробелами, их разделяющие.
        /// </summary>
        public static string NotValidIntegerEnum {
            get {
                return ResourceManager.GetString("NotValidIntegerEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;КИН известного родителя&quot;не должно быть 
        ///пустым и может содержать только цифры.
        /// </summary>
        public static string NotValidOneParent {
            get {
                return ResourceManager.GetString("NotValidOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введен не верный пароль.
        /// </summary>
        public static string NotValidPassword {
            get {
                return ResourceManager.GetString("NotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;КИН второго родителя&quot; не должно быть пустым
        ///и может содержать только цифры.
        /// </summary>
        public static string NotValidSecondParent {
            get {
                return ResourceManager.GetString("NotValidSecondParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В перечислении {0}, не найдено значение {1}.
        /// </summary>
        public static string NotValueInEnum {
            get {
                return ResourceManager.GetString("NotValueInEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение переменной {0} не должно быть Null.
        /// </summary>
        public static string ValueIsNull {
            get {
                return ResourceManager.GetString("ValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элементы справочника успешно сопоставленны.
        /// </summary>
        public static string VocabulareCompared {
            get {
                return ResourceManager.GetString("VocabulareCompared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При сопоставлении элементов справочника,произошла ошибка! Все внесенные изменения были отменены, и справочник остался в прежнем состоянии..
        /// </summary>
        public static string VocabulareNotCompared {
            get {
                return ResourceManager.GetString("VocabulareNotCompared", resourceCulture);
            }
        }
    }
}
