//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resDataNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resDataNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneLibrary.resDataNames", typeof(resDataNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все эксперты.
        /// </summary>
        public static string allExperts {
            get {
                return ResourceManager.GetString("allExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все поля.
        /// </summary>
        public static string allFields {
            get {
                return ResourceManager.GetString("allFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        public static string archive {
            get {
                return ResourceManager.GetString("archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно для карточки ИКЛ.
        /// </summary>
        public static string AvailableToIkl {
            get {
                return ResourceManager.GetString("AvailableToIkl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для карточки {0} будут установлены совпадения
        ///со следюущими карточками: 
        ///{1}.
        /// </summary>
        public static string CardItemMessage {
            get {
                return ResourceManager.GetString("CardItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение профиля карточки {0}, список выбранных аллелей {1}.
        /// </summary>
        public static string ChangeCardProfile {
            get {
                return ResourceManager.GetString("ChangeCardProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В диапазоне.
        /// </summary>
        public static string cndBetween {
            get {
                return ResourceManager.GetString("cndBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержит.
        /// </summary>
        public static string cndConsist {
            get {
                return ResourceManager.GetString("cndConsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заканчивается.
        /// </summary>
        public static string cndEndWith {
            get {
                return ResourceManager.GetString("cndEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Равно.
        /// </summary>
        public static string cndEq {
            get {
                return ResourceManager.GetString("cndEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше.
        /// </summary>
        public static string cndGt {
            get {
                return ResourceManager.GetString("cndGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из списка.
        /// </summary>
        public static string cndInCollection {
            get {
                return ResourceManager.GetString("cndInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше.
        /// </summary>
        public static string cndLt {
            get {
                return ResourceManager.GetString("cndLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начинается с.
        /// </summary>
        public static string cndStartWith {
            get {
                return ResourceManager.GetString("cndStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводный отчет.
        /// </summary>
        public static string CombineReport {
            get {
                return ResourceManager.GetString("CombineReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string divTableAddress {
            get {
                return ResourceManager.GetString("divTableAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string divTableID {
            get {
                return ResourceManager.GetString("divTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string divTableName {
            get {
                return ResourceManager.GetString("divTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string divTablePhone {
            get {
                return ResourceManager.GetString("divTablePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Нет данных--.
        /// </summary>
        public static string emptyComboBox {
            get {
                return ResourceManager.GetString("emptyComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение.
        /// </summary>
        public static string expTableDevision {
            get {
                return ResourceManager.GetString("expTableDevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string expTableID {
            get {
                return ResourceManager.GetString("expTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string expTableName {
            get {
                return ResourceManager.GetString("expTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string expTablePatronic {
            get {
                return ResourceManager.GetString("expTablePatronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        public static string expTablePost {
            get {
                return ResourceManager.GetString("expTablePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подпись.
        /// </summary>
        public static string expTableSign {
            get {
                return ResourceManager.GetString("expTableSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string expTableSurname {
            get {
                return ResourceManager.GetString("expTableSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string filterID {
            get {
                return ResourceManager.GetString("filterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string filterName {
            get {
                return ResourceManager.GetString("filterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string filterText {
            get {
                return ResourceManager.GetString("filterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карты.
        /// </summary>
        public static string findCoincidenceCardNumber {
            get {
                return ResourceManager.GetString("findCoincidenceCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип карточки.
        /// </summary>
        public static string findCoincidenceCardType {
            get {
                return ResourceManager.GetString("findCoincidenceCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество несовпадений.
        /// </summary>
        public static string findCoincidenceCount {
            get {
                return ResourceManager.GetString("findCoincidenceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер экспертизы.
        /// </summary>
        public static string findCoincidenceExamNumber {
            get {
                return ResourceManager.GetString("findCoincidenceExamNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер профиля.
        /// </summary>
        public static string findCoincidenceProfile {
            get {
                return ResourceManager.GetString("findCoincidenceProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество локусов учета.
        /// </summary>
        public static string findLocusCount {
            get {
                return ResourceManager.GetString("findLocusCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ( {0} ).
        /// </summary>
        public static string formFindCountOnHeader {
            get {
                return ResourceManager.GetString("formFindCountOnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль карточки {0}.
        /// </summary>
        public static string formFindProfileFrom {
            get {
                return ResourceManager.GetString("formFindProfileFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль совпавшей карточки {0}.
        /// </summary>
        public static string formFindProfileTo {
            get {
                return ResourceManager.GetString("formFindProfileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по карточке {0}.
        /// </summary>
        public static string formFindText {
            get {
                return ResourceManager.GetString("formFindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточка ИК-2 ({0}).
        /// </summary>
        public static string formIk2 {
            get {
                return ResourceManager.GetString("formIk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточка ИКЛ ({0}).
        /// </summary>
        public static string formIkl {
            get {
                return ResourceManager.GetString("formIkl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список форм.
        /// </summary>
        public static string formsList {
            get {
                return ResourceManager.GetString("formsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота.
        /// </summary>
        public static string freqAlleleTableFreq {
            get {
                return ResourceManager.GetString("freqAlleleTableFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллель.
        /// </summary>
        public static string freqAlleleTableName {
            get {
                return ResourceManager.GetString("freqAlleleTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        public static string freqAlleleTableVal {
            get {
                return ResourceManager.GetString("freqAlleleTableVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локусы.
        /// </summary>
        public static string freqLocusTableName {
            get {
                return ResourceManager.GetString("freqLocusTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Част. по умолчанию.
        /// </summary>
        public static string freqTableDefFreq {
            get {
                return ResourceManager.GetString("freqTableDefFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string freqTableDesc {
            get {
                return ResourceManager.GetString("freqTableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string freqTableID {
            get {
                return ResourceManager.GetString("freqTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод.
        /// </summary>
        public static string freqTableName {
            get {
                return ResourceManager.GetString("freqTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты типирования локусов, установленные генотипы.
        /// </summary>
        public static string GeneTableHeader {
            get {
                return ResourceManager.GetString("GeneTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string historyTableAction {
            get {
                return ResourceManager.GetString("historyTableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата/Время.
        /// </summary>
        public static string historyTableDate {
            get {
                return ResourceManager.GetString("historyTableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эксперт.
        /// </summary>
        public static string historyTableExpert {
            get {
                return ResourceManager.GetString("historyTableExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентифицированные карточки.
        /// </summary>
        public static string ident {
            get {
                return ResourceManager.GetString("ident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИК-2.
        /// </summary>
        public static string ik2 {
            get {
                return ResourceManager.GetString("ik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № ИК-2.
        /// </summary>
        public static string ik2TableCardNum {
            get {
                return ResourceManager.GetString("ik2TableCardNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № Уголовного дела.
        /// </summary>
        public static string ik2TableCrimNum {
            get {
                return ResourceManager.GetString("ik2TableCrimNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string ik2TableDateIns {
            get {
                return ResourceManager.GetString("ik2TableDateIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string ik2TableID {
            get {
                return ResourceManager.GetString("ik2TableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потерпевший.
        /// </summary>
        public static string ik2TableVictim {
            get {
                return ResourceManager.GetString("ik2TableVictim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИКЛ.
        /// </summary>
        public static string ikl {
            get {
                return ResourceManager.GetString("ikl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карточки.
        /// </summary>
        public static string iklOrik2TableCardNum {
            get {
                return ResourceManager.GetString("iklOrik2TableCardNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № ИКЛ.
        /// </summary>
        public static string iklTableCardNum {
            get {
                return ResourceManager.GetString("iklTableCardNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № Уголовного дела.
        /// </summary>
        public static string iklTableCrimNum {
            get {
                return ResourceManager.GetString("iklTableCrimNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string iklTableDateIns {
            get {
                return ResourceManager.GetString("iklTableDateIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string iklTableID {
            get {
                return ResourceManager.GetString("iklTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверяемое лицо.
        /// </summary>
        public static string iklTablePerson {
            get {
                return ResourceManager.GetString("iklTablePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string linTableCode {
            get {
                return ResourceManager.GetString("linTableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string linTableID {
            get {
                return ResourceManager.GetString("linTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string linTableOrgan {
            get {
                return ResourceManager.GetString("linTableOrgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список {0}.
        /// </summary>
        public static string listOfCards {
            get {
                return ResourceManager.GetString("listOfCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код МВД.
        /// </summary>
        public static string mvdTableCode {
            get {
                return ResourceManager.GetString("mvdTableCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string mvdTableID {
            get {
                return ResourceManager.GetString("mvdTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string mvdTableName {
            get {
                return ResourceManager.GetString("mvdTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое имя.
        /// </summary>
        public static string mvdTableShortName {
            get {
                return ResourceManager.GetString("mvdTableShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string noteTableName {
            get {
                return ResourceManager.GetString("noteTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все файлы.
        /// </summary>
        public static string openDialogAllFiles {
            get {
                return ResourceManager.GetString("openDialogAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы профилей.
        /// </summary>
        public static string openDialogProfileFiles {
            get {
                return ResourceManager.GetString("openDialogProfileFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл содержащий профили.
        /// </summary>
        public static string openDialogProfiliesTitle {
            get {
                return ResourceManager.GetString("openDialogProfiliesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string orgTableID {
            get {
                return ResourceManager.GetString("orgTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string orgTableName {
            get {
                return ResourceManager.GetString("orgTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string postTableID {
            get {
                return ResourceManager.GetString("postTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название должности.
        /// </summary>
        public static string postTableName {
            get {
                return ResourceManager.GetString("postTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили найденные в файле &quot;{0}&quot;.
        /// </summary>
        public static string profilesFromFile {
            get {
                return ResourceManager.GetString("profilesFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат прямого поиска.
        /// </summary>
        public static string resultDirect {
            get {
                return ResourceManager.GetString("resultDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат поиска 1/2.
        /// </summary>
        public static string resultHalf {
            get {
                return ResourceManager.GetString("resultHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат поиска для ребенка и одного родителя.
        /// </summary>
        public static string resultOneParent {
            get {
                return ResourceManager.GetString("resultOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат поиска для двух родителей.
        /// </summary>
        public static string resultPairParent {
            get {
                return ResourceManager.GetString("resultPairParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все права.
        /// </summary>
        public static string rightAllList {
            get {
                return ResourceManager.GetString("rightAllList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досупные права.
        /// </summary>
        public static string rightForAccept {
            get {
                return ResourceManager.GetString("rightForAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string roleTableID {
            get {
                return ResourceManager.GetString("roleTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string roleTableName {
            get {
                return ResourceManager.GetString("roleTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ч..
        /// </summary>
        public static string shortPart {
            get {
                return ResourceManager.GetString("shortPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to п..
        /// </summary>
        public static string shortPoint {
            get {
                return ResourceManager.GetString("shortPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ст..
        /// </summary>
        public static string shortState {
            get {
                return ResourceManager.GetString("shortState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string sortTableID {
            get {
                return ResourceManager.GetString("sortTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид объекта.
        /// </summary>
        public static string sortTableName {
            get {
                return ResourceManager.GetString("sortTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string sortTableShortName {
            get {
                return ResourceManager.GetString("sortTableShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список карточек.
        /// </summary>
        public static string treeViewCard {
            get {
                return ResourceManager.GetString("treeViewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string ukTableArtcle {
            get {
                return ResourceManager.GetString("ukTableArtcle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        public static string ukTableID {
            get {
                return ResourceManager.GetString("ukTableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string ukTableName {
            get {
                return ResourceManager.GetString("ukTableName", resourceCulture);
            }
        }
    }
}
