//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStudy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStudy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneLibrary.ResourceStudy", typeof(ResourceStudy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллели смеси.
        /// </summary>
        public static string alleleBlend {
            get {
                return ResourceManager.GetString("alleleBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частоты аллелей смеси.
        /// </summary>
        public static string alleleBlendFrequency {
            get {
                return ResourceManager.GetString("alleleBlendFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллель первого предполагаемого родителя.
        /// </summary>
        public static string alleleFristParent {
            get {
                return ResourceManager.GetString("alleleFristParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллели не найдены.
        /// </summary>
        public static string alleleNotFound {
            get {
                return ResourceManager.GetString("alleleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллели лица.
        /// </summary>
        public static string allelePerson {
            get {
                return ResourceManager.GetString("allelePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллель второго предполагаемого родителя.
        /// </summary>
        public static string alleleSecondParent {
            get {
                return ResourceManager.GetString("alleleSecondParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллель предп. лица.
        /// </summary>
        public static string alleleTwoBlend1 {
            get {
                return ResourceManager.GetString("alleleTwoBlend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллель изв. лица.
        /// </summary>
        public static string alleleTwoBlend2 {
            get {
                return ResourceManager.GetString("alleleTwoBlend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллели предп. родителя.
        /// </summary>
        public static string assumedParentAllele {
            get {
                return ResourceManager.GetString("assumedParentAllele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие в смеси: смесь
        ///и предполагаемое лицо.
        /// </summary>
        public static string captionBlend {
            get {
                return ResourceManager.GetString("captionBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие карточки {0} в смеси карточки {1}.
        /// </summary>
        public static string captionCardInBlend {
            get {
                return ResourceManager.GetString("captionCardInBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямая идентификация личности.
        /// </summary>
        public static string captionDirection {
            get {
                return ResourceManager.GetString("captionDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямая идентификация для карточки КИН {0}.
        /// </summary>
        public static string captionForDirectionResult {
            get {
                return ResourceManager.GetString("captionForDirectionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет вероятности для ребенка КИН {0} и родителя КИН {1}.
        /// </summary>
        public static string captionForOneParent {
            get {
                return ResourceManager.GetString("captionForOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет вероятности для двух родителей КИН {0} и КИН {1}.
        /// </summary>
        public static string captionForPairParents {
            get {
                return ResourceManager.GetString("captionForPairParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родство: ребенок,один известный
        ///и один предполагаемый родитель.
        /// </summary>
        public static string captionOneParent {
            get {
                return ResourceManager.GetString("captionOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие в смеси:  известное
        ///и одно предполагаемое лицо.
        /// </summary>
        public static string captionTwoBlend {
            get {
                return ResourceManager.GetString("captionTwoBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родство: ребенок и пара
        ///предполагаемых родителей.
        /// </summary>
        public static string captionTwoParent {
            get {
                return ResourceManager.GetString("captionTwoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to След {0}.
        /// </summary>
        public static string CardIk2 {
            get {
                return ResourceManager.GetString("CardIk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ребенок {0}.
        /// </summary>
        public static string child {
            get {
                return ResourceManager.GetString("child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллель ребенка.
        /// </summary>
        public static string childAllele {
            get {
                return ResourceManager.GetString("childAllele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты {0}.
        /// </summary>
        public static string findResult {
            get {
                return ResourceManager.GetString("findResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формула{0}.
        /// </summary>
        public static string formula {
            get {
                return ResourceManager.GetString("formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0} * (2 - P{0}).
        /// </summary>
        public static string formula1OneParentHomozigotic {
            get {
                return ResourceManager.GetString("formula1OneParentHomozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 * P{0} * (2 - P{0}) * P{1} * (2 - P{1}) - (2 * P{0} * P{1})^2.
        /// </summary>
        public static string formula2OneParentHeterozigotic {
            get {
                return ResourceManager.GetString("formula2OneParentHeterozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (P{0} * (2 - P{0})^2.
        /// </summary>
        public static string formula2OneParentHomozigotic {
            get {
                return ResourceManager.GetString("formula2OneParentHomozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 * (P{0} * P{1}).
        /// </summary>
        public static string formulaHeteroZigoticProbably {
            get {
                return ResourceManager.GetString("formulaHeteroZigoticProbably", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 * P{0} * (2 - P{0}) * P{1} * (2 - P{1}) - 2 * P{0} * P{1} * P{0} * P{1}.
        /// </summary>
        public static string formulaHeterozigoticTooParent {
            get {
                return ResourceManager.GetString("formulaHeterozigoticTooParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0} * (2 - P{0}).
        /// </summary>
        public static string formulaHomozigoticOneParent {
            get {
                return ResourceManager.GetString("formulaHomozigoticOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0} * P{0}.
        /// </summary>
        public static string formulaHomozigoticProbably {
            get {
                return ResourceManager.GetString("formulaHomozigoticProbably", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0} * (2 - P{0})^2.
        /// </summary>
        public static string formulaHomozigoticTooParent {
            get {
                return ResourceManager.GetString("formulaHomozigoticTooParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/{0}.
        /// </summary>
        public static string formulaInversionDirectily {
            get {
                return ResourceManager.GetString("formulaInversionDirectily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (P{0}  + P{1}) * (2 - (P{0} + P{1})).
        /// </summary>
        public static string formulaOneParentHeterozigotic {
            get {
                return ResourceManager.GetString("formulaOneParentHeterozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0} * (2 - P{0}).
        /// </summary>
        public static string formulaOneParentHomozigotic {
            get {
                return ResourceManager.GetString("formulaOneParentHomozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 * P{0}* (2 - P{0}) * P{1} * (2 - P{1} - ((2 * P{0}* P{1}))^2.
        /// </summary>
        public static string formulaSuppHeterozigotic {
            get {
                return ResourceManager.GetString("formulaSuppHeterozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (P{0} * (2 - P{0}))^2.
        /// </summary>
        public static string formulaSuppHomozigotic {
            get {
                return ResourceManager.GetString("formulaSuppHomozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0}^2 + P{1}^2 + 2 * P{0} * P{1}.
        /// </summary>
        public static string formulaTwoBleand1 {
            get {
                return ResourceManager.GetString("formulaTwoBleand1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0}^2 + 2 * P{0} * P{1}.
        /// </summary>
        public static string formulaTwoBleand2 {
            get {
                return ResourceManager.GetString("formulaTwoBleand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0}^2  + 2 * P{0} * P{1} + 2 * P{0} * P{2}.
        /// </summary>
        public static string formulaTwoBleand3 {
            get {
                return ResourceManager.GetString("formulaTwoBleand3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 * P{0} * P{1}.
        /// </summary>
        public static string formulaTwoBleand4 {
            get {
                return ResourceManager.GetString("formulaTwoBleand4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0} * (2 - P{0}).
        /// </summary>
        public static string formulaTwoParent1 {
            get {
                return ResourceManager.GetString("formulaTwoParent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (P{0} + P{1}) * (2 - (P{0}+ P{1})).
        /// </summary>
        public static string formulaTwoParent2 {
            get {
                return ResourceManager.GetString("formulaTwoParent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (P{0} + P{1}) * (2 - (P{0}+ P{1})).
        /// </summary>
        public static string formulaTwoParentProbablyHeterozigotic {
            get {
                return ResourceManager.GetString("formulaTwoParentProbablyHeterozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0} * (2 - P{0}).
        /// </summary>
        public static string formulaTwoParentProbablyHomozigotic {
            get {
                return ResourceManager.GetString("formulaTwoParentProbablyHomozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (P{0} + P{1}) * (2 - (P{0}+ P{1})).
        /// </summary>
        public static string formulaTwoParentRatioHeterozigotic {
            get {
                return ResourceManager.GetString("formulaTwoParentRatioHeterozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P{0} * (2 - P{0}).
        /// </summary>
        public static string formulaTwoParentRatioHomozigotic {
            get {
                return ResourceManager.GetString("formulaTwoParentRatioHomozigotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частоты.
        /// </summary>
        public static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частоты аллелей смеси.
        /// </summary>
        public static string frequencyBlend {
            get {
                return ResourceManager.GetString("frequencyBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частоты аллелей ребенка.
        /// </summary>
        public static string frequencyChild {
            get {
                return ResourceManager.GetString("frequencyChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частоты аллелей предполагаемого родителя.
        /// </summary>
        public static string frequencyParent {
            get {
                return ResourceManager.GetString("frequencyParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to След содержит более 4 аллелей в локусе {0}.
        /// </summary>
        public static string Ik2Gh2 {
            get {
                return ResourceManager.GetString("Ik2Gh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллель извест. родителя.
        /// </summary>
        public static string knownParentAllele {
            get {
                return ResourceManager.GetString("knownParentAllele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта {0}.
        /// </summary>
        public static string KnownPerson {
            get {
                return ResourceManager.GetString("KnownPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локус.
        /// </summary>
        public static string locus {
            get {
                return ResourceManager.GetString("locus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для карт &quot;{0}&quot; и &quot;{1}&quot; совпадающих локусов не найдено..
        /// </summary>
        public static string locusesNotFound {
            get {
                return ResourceManager.GetString("locusesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для карт {0}, {1} и {2}, совпадающих локусов не найдено.
        /// </summary>
        public static string locusForThreeNotFound {
            get {
                return ResourceManager.GetString("locusForThreeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локус не найден.
        /// </summary>
        public static string locusNotFound {
            get {
                return ResourceManager.GetString("locusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR.
        /// </summary>
        public static string LR {
            get {
                return ResourceManager.GetString("LR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родство: ребенок и один
        ///предполагаемый родитель.
        /// </summary>
        public static string panelChildOneParent {
            get {
                return ResourceManager.GetString("panelChildOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предполагаемый родитель.
        /// </summary>
        public static string panelChildOneParentSecond {
            get {
                return ResourceManager.GetString("panelChildOneParentSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллель предполагаемого родителя.
        /// </summary>
        public static string parentAllele {
            get {
                return ResourceManager.GetString("parentAllele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родитель ({0}).
        /// </summary>
        public static string parentCaption {
            get {
                return ResourceManager.GetString("parentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первый родитель.
        /// </summary>
        public static string parentOne {
            get {
                return ResourceManager.GetString("parentOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Второй родитель.
        /// </summary>
        public static string parentSecond {
            get {
                return ResourceManager.GetString("parentSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль КИН №.
        /// </summary>
        public static string profileKin {
            get {
                return ResourceManager.GetString("profileKin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установление возможности происхождения части
        ///смеси от представленного лица.
        ///Вероятность случайного совпадения..
        /// </summary>
        public static string reportBlend {
            get {
                return ResourceManager.GetString("reportBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установление возможности происхождения части
        ///смеси от представленного лица.
        ///Отношение вероятностей..
        /// </summary>
        public static string reportBlendRatio {
            get {
                return ResourceManager.GetString("reportBlendRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исследование родства ребенка и одного 
        ///предполагаемого родителя.
        ///Вероятность случайного совпадения..
        /// </summary>
        public static string reportDirectOneParent {
            get {
                return ResourceManager.GetString("reportDirectOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямая идентификация генетических признаков. Вероятность случайного совпадения..
        /// </summary>
        public static string reportDirectProbably {
            get {
                return ResourceManager.GetString("reportDirectProbably", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямая идентификация генетических признаков. Отношение вероятностей.
        /// </summary>
        public static string reportDirectRatio {
            get {
                return ResourceManager.GetString("reportDirectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исследование родства ребенка и одного 
        ///предполагаемого родителя.
        ///Отношение вероятностей..
        /// </summary>
        public static string reportRatioOneParent {
            get {
                return ResourceManager.GetString("reportRatioOneParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исследование родства ребенка и двух 
        ///предполагаемых родителей.
        ///Вероятность случайного совпадения..
        /// </summary>
        public static string reportSuppParent {
            get {
                return ResourceManager.GetString("reportSuppParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исследование родства ребенка и двух 
        ///предполагаемых родителей.
        ///Отношение вероятностей..
        /// </summary>
        public static string reportSuppParentRatio {
            get {
                return ResourceManager.GetString("reportSuppParentRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установление возможности происхождения части смеси от 
        /// представленного лица при наличии одного известного..
        /// </summary>
        public static string reportTwoBlend {
            get {
                return ResourceManager.GetString("reportTwoBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установление возможности происхождения части смеси от 
        /// представленного лица при наличии одного известного. Отношение вероятностей.
        /// </summary>
        public static string reportTwoBlendRatio {
            get {
                return ResourceManager.GetString("reportTwoBlendRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исследование родства ребенка, одного известного и
        ///одного неизвестного родителя.
        ///Вероятность случайного совпадения..
        /// </summary>
        public static string reportTwoParent {
            get {
                return ResourceManager.GetString("reportTwoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исследование родства ребенка, одного известного и
        ///одного неизвестного родителя.
        ///Отношение вероятностей..
        /// </summary>
        public static string reportTwoParentRatio {
            get {
                return ResourceManager.GetString("reportTwoParentRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат {0}.
        /// </summary>
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вероятность случайного 
        ///совпадения:.
        /// </summary>
        public static string resultProbably {
            get {
                return ResourceManager.GetString("resultProbably", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отношение 
        ///правдоподобия:.
        /// </summary>
        public static string resultRatio {
            get {
                return ResourceManager.GetString("resultRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого:.
        /// </summary>
        public static string resultSummary {
            get {
                return ResourceManager.GetString("resultSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта {0}.
        /// </summary>
        public static string UnknownPerson {
            get {
                return ResourceManager.GetString("UnknownPerson", resourceCulture);
            }
        }
    }
}
