//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _32 {
            get {
                object obj = ResourceManager.GetObject("_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_Bookmark {
            get {
                object obj = ResourceManager.GetObject("Add Bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_Card {
            get {
                object obj = ResourceManager.GetObject("Add Card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_Folder {
            get {
                object obj = ResourceManager.GetObject("Add Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_Separator {
            get {
                object obj = ResourceManager.GetObject("Add Separator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_Tab {
            get {
                object obj = ResourceManager.GetObject("Add Tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_to_Favourites {
            get {
                object obj = ResourceManager.GetObject("Add to Favourites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_Window_1 {
            get {
                object obj = ResourceManager.GetObject("Add Window 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add_Window_2 {
            get {
                object obj = ResourceManager.GetObject("Add Window 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Address_Book {
            get {
                object obj = ResourceManager.GetObject("Address Book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Advanced_Options {
            get {
                object obj = ResourceManager.GetObject("Advanced Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string AllData {
            get {
                return ResourceManager.GetString("AllData", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Anchor {
            get {
                object obj = ResourceManager.GetObject("Anchor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивы.
        /// </summary>
        internal static string areaFindArchive {
            get {
                return ResourceManager.GetString("areaFindArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карты ИК-2.
        /// </summary>
        internal static string areaFindIk2 {
            get {
                return ResourceManager.GetString("areaFindIk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карты ИКЛ.
        /// </summary>
        internal static string areaFindIkl {
            get {
                return ResourceManager.GetString("areaFindIkl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Attach {
            get {
                object obj = ResourceManager.GetObject("Attach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back___Previous {
            get {
                object obj = ResourceManager.GetObject("Back - Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back_2 {
            get {
                object obj = ResourceManager.GetObject("Back 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Block_Junk_Mail {
            get {
                object obj = ResourceManager.GetObject("Block Junk Mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bookmarks_1 {
            get {
                object obj = ResourceManager.GetObject("Bookmarks 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bookmarks_2 {
            get {
                object obj = ResourceManager.GetObject("Bookmarks 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bookmarks_3 {
            get {
                object obj = ResourceManager.GetObject("Bookmarks 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bookmarks_4 {
            get {
                object obj = ResourceManager.GetObject("Bookmarks 4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Browse_1 {
            get {
                object obj = ResourceManager.GetObject("Browse 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Browse_2 {
            get {
                object obj = ResourceManager.GetObject("Browse 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Browse_3 {
            get {
                object obj = ResourceManager.GetObject("Browse 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar_Day {
            get {
                object obj = ResourceManager.GetObject("Calendar Day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar_Month {
            get {
                object obj = ResourceManager.GetObject("Calendar Month", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar_Multiweek {
            get {
                object obj = ResourceManager.GetObject("Calendar Multiweek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar_Week {
            get {
                object obj = ResourceManager.GetObject("Calendar Week", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес (место проишествия).
        /// </summary>
        internal static string cardAddress {
            get {
                return ResourceManager.GetString("cardAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество ДНК.
        /// </summary>
        internal static string cardAmount {
            get {
                return ResourceManager.GetString("cardAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служебные отметки.
        /// </summary>
        internal static string cardAncillary {
            get {
                return ResourceManager.GetString("cardAncillary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область поиска.
        /// </summary>
        internal static string cardAreaFind {
            get {
                return ResourceManager.GetString("cardAreaFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код вида учета.
        /// </summary>
        internal static string cardCodeAccount {
            get {
                return ResourceManager.GetString("cardCodeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код горрайлиноргана.
        /// </summary>
        internal static string cardCodeLin {
            get {
                return ResourceManager.GetString("cardCodeLin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код МВД, ГУВД, УВД субъекта федерации.
        /// </summary>
        internal static string cardCodeMvd {
            get {
                return ResourceManager.GetString("cardCodeMvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Концентрация ДНК.
        /// </summary>
        internal static string cardConcent {
            get {
                return ResourceManager.GetString("cardConcent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установленные совпадения.
        /// </summary>
        internal static string cardConclusion {
            get {
                return ResourceManager.GetString("cardConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата заполнения.
        /// </summary>
        internal static string cardCreateData {
            get {
                return ResourceManager.GetString("cardCreateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата совершения преступления.
        /// </summary>
        internal static string cardCrimDate {
            get {
                return ResourceManager.GetString("cardCrimDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № Уголовного дела.
        /// </summary>
        internal static string cardCrimNumber {
            get {
                return ResourceManager.GetString("cardCrimNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта оформлена.
        /// </summary>
        internal static string cardDepartment {
            get {
                return ResourceManager.GetString("cardDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата экспертизы.
        /// </summary>
        internal static string cardExamDate {
            get {
                return ResourceManager.GetString("cardExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер экспертизы.
        /// </summary>
        internal static string cardExamNumber {
            get {
                return ResourceManager.GetString("cardExamNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эксперт.
        /// </summary>
        internal static string cardExpert {
            get {
                return ResourceManager.GetString("cardExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заключение эксперта.
        /// </summary>
        internal static string cardExpertConclusion {
            get {
                return ResourceManager.GetString("cardExpertConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подпись эксперта.
        /// </summary>
        internal static string cardExpertSign {
            get {
                return ResourceManager.GetString("cardExpertSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИН.
        /// </summary>
        internal static string cardId {
            get {
                return ResourceManager.GetString("cardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        internal static string cardIk2Category {
            get {
                return ResourceManager.GetString("cardIk2Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № ИК-2.
        /// </summary>
        internal static string cardIk2Number {
            get {
                return ResourceManager.GetString("cardIk2Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид объекта.
        /// </summary>
        internal static string cardIk2Sort {
            get {
                return ResourceManager.GetString("cardIk2Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        internal static string cardIklCategory {
            get {
                return ResourceManager.GetString("cardIklCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № ИКЛ.
        /// </summary>
        internal static string cardIklNumber {
            get {
                return ResourceManager.GetString("cardIklNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карты.
        /// </summary>
        internal static string cardNumber {
            get {
                return ResourceManager.GetString("cardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект.
        /// </summary>
        internal static string cardObject {
            get {
                return ResourceManager.GetString("cardObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Орган назначивший экспертизу.
        /// </summary>
        internal static string cardOrgan {
            get {
                return ResourceManager.GetString("cardOrgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения о лице.
        /// </summary>
        internal static string cardPersonInfo {
            get {
                return ResourceManager.GetString("cardPersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер пятна.
        /// </summary>
        internal static string cardSize {
            get {
                return ResourceManager.GetString("cardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверяемое лицо.
        /// </summary>
        internal static string cardSuspect {
            get {
                return ResourceManager.GetString("cardSuspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья и часть УК.
        /// </summary>
        internal static string cardUkNumber {
            get {
                return ResourceManager.GetString("cardUkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потерпевший.
        /// </summary>
        internal static string cardVictim {
            get {
                return ResourceManager.GetString("cardVictim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год постановки на учет.
        /// </summary>
        internal static string cardYear {
            get {
                return ResourceManager.GetString("cardYear", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Chat {
            get {
                object obj = ResourceManager.GetObject("Chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chat_2 {
            get {
                object obj = ResourceManager.GetObject("Chat 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить 
        ///выбранные элементы?.
        /// </summary>
        internal static string ConfirmDictDel {
            get {
                return ResourceManager.GetString("ConfirmDictDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь:.
        /// </summary>
        internal static string ConnectedUser {
            get {
                return ResourceManager.GetString("ConnectedUser", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Contacts {
            get {
                object obj = ResourceManager.GetObject("Contacts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to данные на.
        /// </summary>
        internal static string DataOn {
            get {
                return ResourceManager.GetString("DataOn", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Email_App_Icon {
            get {
                object obj = ResourceManager.GetObject("Email App Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Email_Display {
            get {
                object obj = ResourceManager.GetObject("Email Display", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Email_Envelope {
            get {
                object obj = ResourceManager.GetObject("Email Envelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Extensions {
            get {
                object obj = ResourceManager.GetObject("Extensions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Favourites {
            get {
                object obj = ResourceManager.GetObject("Favourites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля отображаемые в отчете.
        /// </summary>
        internal static string FieldReport {
            get {
                return ResourceManager.GetString("FieldReport", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установленные фильтры.
        /// </summary>
        internal static string filterCard {
            get {
                return ResourceManager.GetString("filterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточки ИК-2.
        /// </summary>
        internal static string filterNameIk2 {
            get {
                return ResourceManager.GetString("filterNameIk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточки ИКЛ.
        /// </summary>
        internal static string filterNameIkl {
            get {
                return ResourceManager.GetString("filterNameIkl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Fonts_1 {
            get {
                object obj = ResourceManager.GetObject("Fonts 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fonts_2 {
            get {
                object obj = ResourceManager.GetObject("Fonts 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forward___Next {
            get {
                object obj = ResourceManager.GetObject("Forward - Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forward_2 {
            get {
                object obj = ResourceManager.GetObject("Forward 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forward_Email {
            get {
                object obj = ResourceManager.GetObject("Forward Email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap General_Options {
            get {
                object obj = ResourceManager.GetObject("General Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Get_Mail {
            get {
                object obj = ResourceManager.GetObject("Get Mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Go {
            get {
                object obj = ResourceManager.GetObject("Go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap H__Line {
            get {
                object obj = ResourceManager.GetObject("H. Line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по части слова.
        /// </summary>
        internal static string IsPartValue {
            get {
                return ResourceManager.GetString("IsPartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать в отчете.
        /// </summary>
        internal static string IsReportShow {
            get {
                return ResourceManager.GetString("IsReportShow", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Link {
            get {
                object obj = ResourceManager.GetObject("Link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap List {
            get {
                object obj = ResourceManager.GetObject("List", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gene LIbrary.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Move {
            get {
                object obj = ResourceManager.GetObject("Move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New_Doc {
            get {
                object obj = ResourceManager.GetObject("New Doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New_Folder {
            get {
                object obj = ResourceManager.GetObject("New Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New_Window {
            get {
                object obj = ResourceManager.GetObject("New Window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая карта ИКЛ.
        /// </summary>
        internal static string NewIkl {
            get {
                return ResourceManager.GetString("NewIkl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        internal static string NoDate {
            get {
                return ResourceManager.GetString("NoDate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Properties {
            get {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Publish {
            get {
                object obj = ResourceManager.GetObject("Publish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quote {
            get {
                object obj = ResourceManager.GetObject("Quote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quote_2 {
            get {
                object obj = ResourceManager.GetObject("Quote 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rename___Edit {
            get {
                object obj = ResourceManager.GetObject("Rename - Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reply {
            get {
                object obj = ResourceManager.GetObject("Reply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reply_to_All {
            get {
                object obj = ResourceManager.GetObject("Reply to All", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка системы!
        ///Произошла ошибка, которая не может быть обработана. 
        ///Возможно эта ошибка связана с отсутствием связи с базой данных, исчерпанием системных ресурсов или неправильной работой сторонних приложений. Ниже представлена более подробная информация об ошибке. Если причина возникновения ошибки не ясна и ошибка повторяется, отправьте информацию об ошибке разработчикам системы..
        /// </summary>
        internal static string rsGlobErrorMsg {
            get {
                return ResourceManager.GetString("rsGlobErrorMsg", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveAndGo {
            get {
                object obj = ResourceManager.GetObject("SaveAndGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Security {
            get {
                object obj = ResourceManager.GetObject("Security", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Send {
            get {
                object obj = ResourceManager.GetObject("Send", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Send_2 {
            get {
                object obj = ResourceManager.GetObject("Send 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Send_Later {
            get {
                object obj = ResourceManager.GetObject("Send Later", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spell {
            get {
                object obj = ResourceManager.GetObject("Spell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_2 {
            get {
                object obj = ResourceManager.GetObject("Stop 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table_1 {
            get {
                object obj = ResourceManager.GetObject("Table 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Themes {
            get {
                object obj = ResourceManager.GetObject("Themes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Themes_2 {
            get {
                object obj = ResourceManager.GetObject("Themes 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определен тип дочерней формы.
        /// </summary>
        internal static string UnknownCardType {
            get {
                return ResourceManager.GetString("UnknownCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный поставщик данных.
        /// </summary>
        internal static string UnknownDB {
            get {
                return ResourceManager.GetString("UnknownDB", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UnSecurity {
            get {
                object obj = ResourceManager.GetObject("UnSecurity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_Doc {
            get {
                object obj = ResourceManager.GetObject("View Doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Write {
            get {
                object obj = ResourceManager.GetObject("Write", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
